### ISSUE TITLE
ErrorException: Undefined property: stdClass::$status_message

### ISSUE THREAD

**Issue by deri387** [veritrans/veritrans-php#105]
ErrorException: Undefined property: stdClass::$status_message

**Comment by dimz1690** [comment]
I had same error like that, when using Veritrans_Transaction::status($orderid).
any solution ?

**Comment by rizdaprasetya** [comment]
Hi all, as [announced on the readme file](https://github.com/veritrans/veritrans-php#:~:text=Please%20use%20the%20updated%20and%20composer%20compatible%20library%3A%20Midtrans%20PHP.%20For%20better%20more%20modern%20composer%20compatibility.) please use and update to use https://github.com/Midtrans/midtrans-php instead.

Also the issue can be caused of: Order ID not found or never created on Midtrans, wrong isProduction value, or wrong serverKey value. Will be closing issue here, since this repo is no longer monitored. Please open issue on the new repo if the issue still persist. thanks.
