### ISSUE TITLE
Getting status error on HttpRequest using java !

### ISSUE THREAD

**Issue by 13yewebster** [veritrans/veritrans-php#23]
This is data json in body :

 {"payment_type":"credit_card","credit_card":{"token_id":"481111-1114-a20971a7-1d82-4813-bd9c-561d8797177c","bank":"bni","save_token_id":"481111-1114-a20971a7-1d82-4813-bd9c-561d8797177c"},"transaction_details":{"order_id":1426147098232,"gross_amount":"200500"},"item_details":{"id":"item1","price":200500,"quantity":1,"name":"Adidas f50"},"customer_details":{"first_name":"Andri","last_name":"Setiawan","email":"andri@setiawan.com","phone":"081322311801","billing_address":{"first_name":"Andri","last_name":"Setiawan","address":"Karet Belakang 15A, Setiabudi.","city":"Jakarta","postal_code":"51161","phone":"081322311801","country_code":"IDN"},"shipping_address":{"first_name":"John","last_name":"Watson","address":"Bakerstreet 221B.","city":"Jakarta","postal_code":"51162","phone":"081322311801","country_code":"IDN"}}}

This is my code : 

	JSONObject jsonObject = JSONObject.fromObject(dataHash); // dataHash is Map<String, Object>
	DefaultHttpClient httpClient = new DefaultHttpClient();
	HttpPost httpPost = new HttpPost(url);

        httpPost.setHeader("Accept", "application/json");
        httpPost.setHeader("Content-type", "application/json");
        httpPost.setHeader("Authorization: Basic", Base64.encodeBase64(url.getBytes()).toString());
            
	StringEntity se = new StringEntity(jsonObject.toString());  
	httpPost.setEntity(se);

	HttpResponse httpResponse = httpClient.execute(httpPost);

This error what i've got ?
{
     "status_code" : "413",
     "status_message" : "The request cannot be processed due to malformed syntax in the request body"
}

Help me please ? If ure using java..

**Comment by Paxa** [comment]
Hello, sorry for late reply.

That error can mean that wrong json format.

Your problem is: `credit_card -> save_token_id` should be boolean (true). Here is documentation: http://docs.veritrans.co.id/sandbox/other_features.html#two-click

Did you find this example in documentation? We will fix it if so

Here's working example:

```json
{  
   "payment_type":"credit_card",
   "credit_card":{  
      "token_id":"481111-1114-a20971a7-1d82-4813-bd9c-561d8797177c",
      "bank":"bni",
      "save_token_id": true
   },
   "transaction_details":{  
      "order_id":1426147098232,
      "gross_amount":"200500"
   },
   "item_details":{  
      "id":"item1",
      "price":200500,
      "quantity":1,
      "name":"Adidas f50"
   },
   "customer_details":{  
      "first_name":"Andri",
      "last_name":"Setiawan",
      "email":"andri@setiawan.com",
      "phone":"081322311801",
      "billing_address":{  
         "first_name":"Andri",
         "last_name":"Setiawan",
         "address":"Karet Belakang 15A, Setiabudi.",
         "city":"Jakarta",
         "postal_code":"51161",
         "phone":"081322311801",
         "country_code":"IDN"
      },
      "shipping_address":{
         "first_name":"John",
         "last_name":"Watson",
         "address":"Bakerstreet 221B.",
         "city":"Jakarta",
         "postal_code":"51162",
         "phone":"081322311801",
         "country_code":"IDN"
      }
   }
}
```

---

Simple 2-click work like this: first time you do just usual transaction, and add `credit_card -> save_token_id = true`. If transaction is successful, we will save that credit card number, you can see it in response json for `POST /v2/charge`.

After that your customer can make transaction by only entering cvv code. So second time you need to make get token request with saved token + cvv (again), example: https://api.sandbox.veritrans.co.id/v2/token?client_key=e668b029-db9d-46fd-b863-e9056f404204&token_id=4811113d90f540-6c0a-410f-bf86-cc988957cd89&card_cvv=234&two_click=true

New token (generated with saved token + cvv) can use to charge that credit card again. (When you use saved token you don't need to add `credit_card -> save_token_id = true`)

**Comment by Paxa** [comment]
@13yewebster Could you make it works?

**Comment by 13yewebster** [comment]
Yes i could, Thanks ;)
