### ISSUE TITLE
Inconsisten requirement option for item_details parameter in VtWeb

### ISSUE THREAD

**Issue by keripix** [veritrans/veritrans-php#37]
Base on the `VtWeb.php` file on line 15 - 21, it seems that when `item_details` parameter are provided, the `quantity` and `price` fields become mandatory for each of the items inside `item_details`.

This is different from the http://docs.veritrans.co.id/en/api/methods.html page, where it states that the `quality` and `price` fields are optional.

**Comment by robeth** [comment]
Hi @keripix, thank you for using veritrans-php.

In the new code base, line 15-21, that you've referred, have been moved to line 38 - 44 ([VtWeb.php](https://github.com/veritrans/veritrans-php/blob/master/Veritrans/VtWeb.php)).

It turns out that our [documentation](http://docs.veritrans.co.id/en/api/methods.html) is wrong. The code is right.

- `item_details` is **optional**.
- attribute `id`, `price`, `quantity`, & `name` of item is **mandatory** if item is exist

Thank you for reporting this issue. Our support team will update the documentation page :smile:

**Comment by yocki-s** [comment]
docs already update

**Comment by Dimasdanz** [comment]
Sorry, but the doc is not updated. [https://api-docs.midtrans.com/#item-details](https://api-docs.midtrans.com/#item-details)

**Comment by yocki-s** [comment]
hi @Dimasdanz 

Thanks for your information.

As our documentation said, for now this is the specs:

- `item_details` is **optional**.
- attribute `price`, `quantity`, & `name` of item is **mandatory** if item is exist

**Comment by fahrirusliyadi** [comment]
In [the doc](https://snap-docs.midtrans.com/#json-objects), the item `id` of `item_details` is optional, but [the code](https://github.com/veritrans/veritrans-php/blob/master/Veritrans/Sanitizer.php#L36-L39) does not check its existence.
