### ISSUE TITLE
About item_details field and Validation Error

### ISSUE THREAD

**Issue by imanrp** [veritrans/veritrans-php#50]
Starting about last month, I keep getting these 'Validation Error' emails:
![sc_1](https://cloud.githubusercontent.com/assets/2027300/15532835/eabf03bc-228b-11e6-9d07-add1b65fb0a9.png)

I indeed am not sending 'item_details' to the transaction request because I don't need them (already covered in 'transaction_details') and the Documentation stated that it's OPTIONAL
![sc_2](https://cloud.githubusercontent.com/assets/2027300/15532836/eabff204-228b-11e6-82de-6919956ffd73.png)

- In my opinion, it should be really optional because it's not applicable to all cases and I think shouldn't be getting those errors. I hope you can take a look at it.

-  Also,  when this kind of Validation Error happens, what will happen exactly to the transaction?

Thank you!
(Sorry if I'm this is the wrong place to post this issue!)

**Comment by yocki-s** [comment]
Hi @imanrp,

Could you send the question to support@veritrans.co.id. We need several informations to check the issue.

btw, 
- Also, when this kind of Validation Error happens, what will happen exactly to the transaction?
The transaction will failed. Since you get error, customer not redirect to VT-Web.

Thanks

**Comment by robeth** [comment]
hi mas @yocki-s,

The VT-Web link will be generated successfully. The error will happen when customer try to pay using VT-Web.

Because as you say, some payment method need `item_details` to exist.
