### ISSUE TITLE
Can't retrieve post from notification

### ISSUE THREAD

**Issue by yuliantosb** [veritrans/veritrans-php#83]
Hello, I have some issues, I can't get the post from notification, but if I get all the data appear, but if I get specificly the key, the data not appear even getting error,

here is my code

```
public function store()
{
      $json_result = file_get_contents('php://input');
      $result = json_decode($json_result);
}
```

if I get variable `$result`, the data appear like this

`{"masked_card":"411111-1111","approval_code":"000000","bank":"mandiri","eci":"02","transaction_time":"2014-04-07 16:22:36","gross_amount":"2700","order_id":"2014040745","payment_type":"credit_card","signature_key":"5d7df20ab2dfe91451c28f76f7dbdf3bcbb02555961f358cbe6a57f02e4c0ec72fa54f773bf3e196c2ae4df66f9b3fc71ed5167c49f7995d9efbda5e03d79f1d","status_code":"200","transaction_id":"826acc53-14e0-4ae7-95e2-845bf0311579","transaction_status":"capture","fraud_status":"accept","status_message":"Veritrans payment notification"}
`

but if I get by the key, become error

`$result->order_id;`

the error said
`error, trying to property non object`

then I try to change it become array

```
$result = json_decode($json_result, true);
$result['order_id'];

```
then, error again, the error said
`illegal string offset order_id`

is there something missing?

Sorry my English is bad, Thanks

**Comment by rizdaprasetya** [comment]
Hi @yuliantosb 

Your first code should be right. 

The issue is in "Send Test Notification" feature. Same issue here:
https://github.com/veritrans/veritrans-php/issues/73#issuecomment-384583154

The solution is for now ignore "Send Test Notification" and do sandbox transaction to trigger proper notification that will be sent to your notification handler code.

Thanks
