### ISSUE TITLE
transaction_time timezone

### ISSUE THREAD

**Issue by samelement** [veritrans/veritrans-php#98]
Hello team,
I just landed on Midtrans and tried to place some transaction in sandbox. When I made a status request as follow:

`$objStatus = Veritrans_Transaction::status($order_id);`

I receive a transaction_time without any timezone attached as follow: 

` [transaction_time] => 2019-04-24 09:37:38`

Thanks..!

**Comment by rizdaprasetya** [comment]
Hi @samelement 

Currently that behavior is expected. Midtrans is Payment Gateway that currently focus on serving Indonesia market. So all timestamp should be considered as our server local time, which is Jakarta local time: UTC +7 (which also timezone where majority of the merchant is using).
So if you are using it outside that timezone, please manually convert it to your local timezone from UTC+7.

Disclaimer: Since the timestamp come from API (and we are not planning to handle it on library/client level), this issue is not directly related to this repo. Therefore no changes will be made.

Thanks.
